name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install libusb pkg-config

      - name: Run tests
        run: sh run_tests.sh

      - name: Build
        run: sh build.sh
